language: python
python:
 - "3.5"
 - "3.6"
 - "3.8"
 - "3.9"
env:
 - LINT=
 - LINT=1
install:
 - npm install -g jshint
 - pip install py-mini-racer
 - pip install flake8
 - pip install wq.app
script:
 - ./runtests.sh
